version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOMAIN=qai.quantum-ai.asia
      - FRONTEND_URL=https://qai.quantum-ai.asia
      - DATABASE_URL=postgresql://user:password@db:5432/cyberdb
      # Add other env vars like JWT_SECRET, OAUTH keys, Slack tokens here
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/ssl/quantum-ai.asia:ro
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cyberdb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: