# .github/workflows/deploy.yml

name: Build & Deploy Fullstack to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the code
      - uses: actions/checkout@v3

      # 2) Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # 3) Set up gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 4) Configure Docker to push to GCR
      - name: Configure Docker
        run: gcloud auth configure-docker

      # 5) Build & push Docker image
      - name: Build & Push Docker image
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/ai-cyber-fullstack:latest"
          docker build -t $IMAGE .
          docker push $IMAGE

      # 6) Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ai-cyber-fullstack \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/ai-cyber-fullstack:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            # --- ADD a secure connection to Cloud SQL ---
            --add-cloudsql-instances ${{ secrets.DB_CONNECTION_NAME }} \
            # --- ADD the database URL as a secret ---
            --set-env-vars="DATABASE_URL=postgresql+asyncpg://user:${{ secrets.DB_PASSWORD }}@/.s.PGSQL.5432/cyberdb"
             # --- ADD/UPDATE these environment variables for your custom domain ---
            --update-env-vars="GOOGLE_REDIRECT_URI=https://quantum-ai.asia/api/auth/callback" \
            --update-env-vars="FRONTEND_URL=https://quantum-ai.asia" \
            --update-env-vars="DOMAIN=quantum-ai.asia"
